name: skip typing sudo
on:
  workflow_dispatch:

# Defaults saves you from typing sudo over and over
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: HOME=/root sudo -E bash {0}

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: |
          whoami | tee /i-am-root
          ls -la /i-am-root
          
      - run: |
          echo $HOME
          ls -la ~/
          ls -la /root

      - run: |
          echo $HOME
        shell: sudo bash {0}
